name: app_tasks_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_slidable: ^2.0.0
  shared_preferences: ^2.0.15
  bitsdojo_window: ^0.1.5
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: false
  android: true
  image_path: 'assets/icons/icon.png'
  web:
    generate: true
    image_path: 'assets/icons/icon.png'
  windows:
    generate: true
    image_path: 'assets/icons/icon.png'
    icon_size: 48
